server {
    listen       80;
    listen  [::]:80;
    charset utf-8;
    ssl_protocols       TLSv1.2 TLSv1.3;
    server_name  localhost;

    client_max_body_size 100M;

    location ^~/trial/ {
        root   /work/static/;
        index  index.html;
        try_files $uri $uri/ /trial/index.html;
    }

    location / {
        root   /work/static/trial;
        index  index.html;
        try_files $uri $uri/ /trial/index.html;
    }
}